-- Dimension table for organizations
CREATE TABLE dim_organizations ( --primary keys/surrogate keys autogenerated by postgresql as uuid, while for integers as PK/SK this: ORGANIZATION_KEY INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  
     ORGANIZATION_ID UUID PRIMARY KEY, --Create a column for natural keys(id from the raw csv file)
     NAME    VARCHAR(255) NOT NULL,
     ADDRESS VARCHAR(255) NOT NULL,
     CITY    VARCHAR(30) NOT NULL,
     STATE   VARCHAR(30) NOT NULL,
     ZIP     VARCHAR(20) NOT NULL
                              )
;

-- Dimension table for providers
CREATE TABLE dim_providers (
     PROVIDER_ID UUID PRIMARY KEY, --Create a column for natural keys(id from the raw csv file)
     NAME       VARCHAR(255) NOT NULL,
     ORGANIZATION_ID UUID,
     GENDER     CHAR(1) CHECK (GENDER IN('M', 'F')), --CHECK constraint to ensure that the gender column only contains valid values ('M' or 'F')
     SPECIALTY  VARCHAR(255) NOT NULL,
     CITY       VARCHAR(255) NOT NULL,
     STATE      VARCHAR(255) NOT NULL,
     ZIP        VARCHAR(20) NOT NULL,
     CONSTRAINT  fk_dim_providers_organization
       FOREIGN KEY (ORGANIZATION_ID)
           REFERENCES dim_organization (ORGANIZATION_ID) --Table level foreign key constraint to link dim_providers to dim_organizations(You define the column first, then add the foreign key as a separate table constraint.), for inline foreign key constraint, you can define it in the column definition itself, like this: ORGANIZATION_ID UUID REFERENCES dim_organizations(ORGANIZATION_ID) for PostgreSQL.
                         )
;

--Dimension table for payer
CREATE TABLE dim_payers (
     PAYER_ID UUID PRIMARY KEY,
     NAME               VARCHAR(255) NOT NULL,
     OWNERSHIP          VARCHAR(255) NOT NULL, 
     STATE_HEADQUARTERED VARCHAR(255) NULL
                        )
;

-- Dimension table for patients
CREATE TABLE dim_patients (
     PATIENT_ID UUID PRIMARY KEY,
     BIRTHDATE DATE NOT NULL,
     DEATHDATE DATE NULL,
     MARITAL    CHAR(1) CHECK (MARITAL IN('M', 'S', 'D')) NULL,
     RACE       VARCHAR(30) NOT NULL,
     ETHNICITY  VARCHAR(30) NOT NULL,
     GENDER     CHAR(1) CHECK (GENDER IN('M', 'F')),
     CITY       VARCHAR(30) NOT NULL,
     STATE      VARCHAR(30) NOT NULL,
     ZIP        VARCHAR(20) NOT NULL
                        )
 ;

--Fact table for encounter
CREATE TABLE fact_encounters (
     ENCOUNTER_ID UUID PRIMARY KEY,,
     START TIMESTAMPZ NOT NULL,
     STOP TIMESTAMPZ NOT NULL,
     PATIENT_ID UUID NOT NULL,
     ORGANIZATION_ID UUID NOT NULL,
     PROVIDER_ID UUID NOT NULL,
     PAYER_ID UUID NOT NULL,
     ENCOUNTER_DATE DATE NOT NULL,
     ENCOUNTERCLASS VARCHAR(255) NOT NULL,
     ENCOUNTER_CODE VARCHAR(255) NOT NULL,
     ENCOUNTER_DESCRIPTION TEXT NULL,
     TOTAL_CLAIM_COST DECIMAL(10, 2) NOT NULL,
     PAYER_COVERAGE DECIMAL(10, 2) NOT NULL,

    CONSTRAINT fk_fact_encounters_patient
        FOREIGN KEY (PATIENT_ID)
            REFERENCES dim_patients (PATIENT_ID),
    CONSTRAINT fk_fact_encounters_provider
        FOREIGN KEY (PROVIDER_ID)
            REFERENCES dim_providers (PROVIDER_ID),
    CONSTRAINT fk_fact_encounters_organization
        FOREIGN KEY (ORGANIZATION_ID)
            REFERENCES dim_organization (ORGANIZATION_ID),
    CONSTRAINT fk_fact_encounters_payer
        FOREIGN KEY (PAYER_ID)
            REFERENCES dim_payers (PAYER_ID) 

   CONSTRAINT check_fact_encounters_start_stop
            CHECK (STOP >= START)
)
;

--Conditions Fact Table 
CREATE TABLE fact_conditions (
    -- Surrogate Primary Key
    CONDITION_ID UUID PRIMARY KEY, --If you are trying to write constraints PRIMARY KEY, NOT NULL, UNIQUE together on a single column, PRIMARY KEY already   includes both NOT NULL and UNIQUE
    ENCOUNTER_ID UUID NOT NULL REFERENCES fact_encounters(ENCOUNTER_ID) ON DELETE CASCADE,
    PATIENT_ID  UUID NOT NULL REFERENCES dim_patients(PATIENT_ID),
    START   DATE NOT NULL,
    STOP    DATE,
    CONDITION_CODE VARCHAR(50) NOT NULL,
    CONDITION_DESCRIPTION  TEXT NOT NULL,
    CONSTRAINT check_fact_conditions_start_stop
            CHECK (STOP >= START)
                             ) 
;

-- I don't still understand this wrote this part with AI because i found out its good ofr optimization and performance, but i will need to learn more about it, but for now i will just write it down as it is.
-- Indexes on Foreign Keys in Central Fact Table
CREATE INDEX idx_fact_encounters_patient      ON fact_encounters(patient_id);
CREATE INDEX idx_fact_encounters_provider     ON fact_encounters(provider_id);
CREATE INDEX idx_fact_encounters_organization ON fact_encounters(organization_id);
CREATE INDEX idx_fact_encounters_payer        ON fact_encounters(payer_id);

-- Index on Encounter Start Timestamp (Critical for time-series / windowing queries)
CREATE INDEX idx_fact_encounters_start_time   ON fact_encounters(start_timestamp);

-- Indexes on Sibling Fact Table
CREATE INDEX idx_fact_conditions_encounter   ON fact_conditions(encounter_id);
CREATE INDEX idx_fact_conditions_patient     ON fact_conditions(patient_id);